export const SERVERLESSQ_API_SECRET_TOKEN =
  process.env.SERVERLESSQ_API_SECRET_TOKEN!;
export const SERVERLESSQ_API_TOKEN = process.env.SERVERLESSQ_API_TOKEN!;
export const SERVERLESSQ_QUEUE_ID = process.env.SERVERLESSQ_QUEUE_ID!;
export const TELEGRAM_BOT_API_SECRET_TOKEN =
  process.env.TELEGRAM_BOT_API_SECRET_TOKEN!;
export const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN!;
export const VERCEL_URL = process.env.VERCEL_URL!;
